Demo/Controllers/QueueController.cs, Demo/Invocables/DoExpensiveCalculationAndStore.cs, Demo/Startup.cs, Demo/appsettings.Development.json, Docs/Queuing.md, Src/Coravel/Queuing/HostedService/QueuingHost.cs, Src/Coravel/Queuing/Queue.cs
=> Queue Prevents App Close When Tasks Still Running

Demo/Listeners/WriteStaticMessageToConsoleListener.cs, Src/Coravel/Coravel.csproj, Src/Coravel/Events/Dispatcher.cs, Src/Coravel/Scheduling/Schedule/Cron/CronExpression.cs, Src/UnitTests/Events/EventTests.cs
=> Port To Net Standard

README.md
Minor change to readme for net standard update.
=> Docs Adjusted To Reflect .NET Standard Port

Src/Coravel/Scheduling/Schedule/Event/ScheduledEvent.cs, Src/Coravel/Scheduling/Schedule/Scheduler.cs, Src/UnitTests/Scheduling/UnscheduleTests.cs
Internal ability to unschedule events + internal changes to the concurrent collection.
=> Unschedule Events

Src/Coravel/Scheduling/Schedule/Event/ScheduledEvent.cs, Src/Coravel/Scheduling/Schedule/Scheduler.cs, Src/UnitTests/Scheduling/Invocable/InvocableTests.cs, Src/UnitTests/Scheduling/UnscheduleTests.cs
Allows scheduling invocable by passing the type (non-generic).
=> Schedule type

Demo/Invocables/RebuildStaticCachedData.cs, Demo/Invocables/SendNightlyReportsEmailJob.cs, Demo/Invocables/SendPendingNotifications.cs, Demo/Startup.cs, Docs/Scheduler.md, Src/Coravel/Coravel.csproj, Src/Coravel/Scheduling/Schedule/Interfaces/IScheduler.cs, Src/Coravel/Scheduling/Schedule/Scheduler.cs, Src/UnitTests/Scheduling/ScheduleWorkerTests.cs
Adding Schedule Workers feature.
=> Schedule Workers / 2.2.0

Demo/Startup.cs, Docs/Scheduler.md, README.md, Src/Coravel/Scheduling/Schedule/Event/ScheduledEvent.cs, Src/UnitTests/Scheduling/IntervalTests/SchedulerSubMinuteTests.cs
Scheduling for under a minute (per second). Changes the Hosted Service so will release as 3.0.0
=> Sub Minute Scheduling

Docs/Scheduler.md
Before submitting this PR, please make sure:
Otherwise, your PR will probably be rejected
Other Notes:
Coravel is created with a specific vision and philosophy:
- Simple, fluent and straightforward public APIs
- Easy to read documentation that guides users coherently
- Building **useful** features because they really are useful - not just for the sake of adding "more features"
To that effect, don't feel bad when many changes are asked of your PR 😉
=> Update Scheduler.md - fix a typo

README.md
updated BuiltWithDot.Net URL that was not working
Before submitting this PR, please make sure:
Otherwise, your PR will probably be rejected
Other Notes:
Coravel is created with a specific vision and philosophy:
- Simple, fluent and straightforward public APIs
- Easy to read the documentation that guides users coherently
- Building **useful** features because they really are useful - not just for the sake of adding "more features"
To that effect, don't feel bad when many changes are asked of your PR 😉
=> BuiltWithDot.Net URL Fixed

Src/Coravel/Scheduling/Schedule/Interfaces/IScheduledEventConfiguration.cs, Src/Coravel/Scheduling/Schedule/Interfaces/IScheduler.cs, Src/UnitTests/CoravelUnitTests/Scheduling/Invocable/InvocableTests.cs
Exposed internal method to register an invocable via it's type.
=> Invocable by type

.vscode/settings.json, Demo/Controllers/CacheController.cs, Demo/Demo.csproj, DocsV2/docs/Caching/README.md, Src/Coravel.Cache.Database/Coravel.Cache.Database.Core/CacheEntryDBModel.cs, Src/Coravel.Cache.Database/Coravel.Cache.Database.Core/Coravel.Cache.Database.Core.csproj, Src/Coravel.Cache.Database/Coravel.Cache.Database.Core/DatabaseCache.cs, Src/Coravel.Cache.Database/Coravel.Cache.PostgreSQL/Coravel.Cache.PostgreSQL.csproj, Src/Coravel.Cache.Database/Coravel.Cache.SqlServer/Coravel.Cache.SqlServer.csproj, Src/Coravel/Cache/InMemoryCache.cs, Src/Coravel/Cache/Interfaces/ICache.cs, Src/Coravel/Cache/NoCacheEntryException.cs, Src/Coravel/Coravel.csproj, Src/IntegrationTests/TestMvcApp/Controllers/CacheController.cs, Src/IntegrationTests/Tests/Cache/GetAsyncTests.cs, Src/IntegrationTests/Tests/Cache/HasAsyncTests.cs
Added:
`GetAsync`
`HasAsync`
These were added to all the cache drivers.
=> Cache Get And Has Methods

DocsV2/docs/Caching/README.md
Before submitting this PR, please make sure:
Otherwise, your PR will probably be rejected
Other Notes:
Coravel is created with a specific vision and philosophy:
- Simple, fluent and straightforward public APIs
- Easy to read documentation that guides users coherently
- Building **useful** features because they really are useful - not just for the sake of adding "more features"
To that effect, don't feel bad when many changes are asked of your PR 😉
I guess my changes are just fixing a typo, so I didn't create an issue.
=> add GetAsync example

Src/Coravel/Scheduling/Schedule/Scheduler.cs
#Added Invocable type name as a log scope for typed scheduling
#Logging exception instead of excepton message
#Changed level of debug messages
=> Issue 160, made logs more usefull in Scheduler

DocsV2/docs/Mailing/README.md
Fixes https://github.com/jamesmh/coravel/issues/167#issue-623247609
=> Fixed Broken Links in the Mailing section

DocsV2/docs/Queuing/README.md, Src/Coravel/Queuing/Broadcast/QueueTaskCompleted.cs, Src/Coravel/Queuing/Broadcast/QueueTaskStarted.cs, Src/Coravel/Queuing/Interfaces/IQueue.cs, Src/Coravel/Queuing/Queue.cs, Src/Coravel/Queuing/QueueMetrics.cs, Src/UnitTests/CoravelUnitTests/Queuing/CancellableInvocableForQueueTests.cs, Src/UnitTests/CoravelUnitTests/Queuing/QueueBroadcastTests.cs, Src/UnitTests/CoravelUnitTests/Queuing/QueueMetricTests.cs
=> Queue metrics + Expose Task Guid

Src/Coravel/Queuing/Queue.cs, Src/UnitTests/CoravelUnitTests/Queuing/QueueMetricTests.cs
=> Fix not decrementing number of running queue tasks on fail

Src/Coravel/Scheduling/Schedule/Event/ScheduledEvent.cs, Src/Coravel/Scheduling/Schedule/Interfaces/IScheduledEventConfiguration.cs, Src/Coravel/Scheduling/Schedule/Scheduler.cs, Src/UnitTests/CoravelUnitTests/Scheduling/IntervalTests/SchedulerRunAtStartTests.cs
=> run scheduled event once at start

DocsV2/docs/Invocables/README.md, DocsV2/docs/Scheduler/README.md
Just a couple of minor doc fixes.
=> Minor Doc Fixes

DocsV2/docs/Installation/README.md, DocsV2/docs/README.md
Before submitting this PR, please consider:
- If you are fixing something **other than a typo, please always create an issue first**. Otherwise, your PR will probably be rejected.
- You have added unit tests which (a) pass and (b) sufficiently cover your changes
=> minor doc improvements

README.md
Before submitting this PR, please consider:
- If you are fixing something **other than a typo, please always create an issue first**. Otherwise, your PR will probably be rejected.
- You have added unit tests which (a) pass and (b) sufficiently cover your changes
=> readme faq added

DocsV2/docs/Scheduler/README.md, Src/Coravel/Scheduling/Schedule/Event/ScheduledEvent.cs, Src/Coravel/Scheduling/Schedule/Interfaces/IScheduledEventConfiguration.cs, Src/Coravel/Scheduling/Schedule/Scheduler.cs, Src/UnitTests/CoravelUnitTests/Scheduling/RestrictionTests/SchedulerOnce.cs
=> working with tests + docs

DocsV2/docs/Queuing/README.md
Before submitting this PR, please consider:
- If you are fixing something **other than a typo, please always create an issue first**. Otherwise, your PR will probably be rejected.
- You have added unit tests which (a) pass and (b) sufficiently cover your changes
=> Fixed typo

Demo/Startup.cs, Src/Coravel/Coravel.csproj, Src/Coravel/Scheduling/HostedService/SchedulerHost.cs
Addresses https://github.com/jamesmh/coravel/issues/391
=> Remove Logs For Missed Ticks

Src/Coravel.Cache.Database/Coravel.Cache.Database.Core/Coravel.Cache.Database.Core.csproj, Src/Coravel.Cache.Database/Coravel.Cache.PostgreSQL/Coravel.Cache.PostgreSQL.csproj
Update packages with security issues
=> update security issues

Demo/Demo.csproj, Demo/appsettings.Development.json, Demo/appsettings.json, Src/Coravel.Mailer/Coravel.Mailer.csproj
=> update mailer nuget

Demo/Controllers/MailController.cs, Demo/Demo.csproj, DocsV2/docs/Mailing/README.md, Src/Coravel.Mailer/Coravel.Mailer.csproj, Src/Coravel.Mailer/Mail/InlineMailable.cs, Src/Coravel.Mailer/Mail/InlineMailableT.cs, Src/Coravel.Mailer/Mail/Interfaces/ICanSendMail.cs, Src/Coravel.Mailer/Mail/Interfaces/IMailer.cs, Src/Coravel.Mailer/Mail/Mailable.cs, Src/Coravel.Mailer/Mail/Mailers/CanSendMailWrapper.cs, Src/Coravel.Mailer/MailServiceRegistration.cs, Src/IntegrationTests/TestMvcApp/Controllers/MailController.cs, Src/IntegrationTests/Tests/Mail/MailerSmokeTests.cs, Src/UnitTests/MailerUnitTests/Mail/CanSendMailWrapperTests.cs, Src/UnitTests/MailerUnitTests/Mail/InlineMailableTests.cs
Two big improvements to the mailer:
- New approach for customer mailers
- New approach for defining and using mailables
=> New Custom Mailer Approach And Inline Mailables

Demo/Controllers/MailController.cs, DocsV2/docs/Mailing/README.md, Src/Coravel.Mailer/Coravel.Mailer.csproj, Src/Coravel.Mailer/Mail/Interfaces/ICanSendMail.cs, Src/Coravel.Mailer/Mail/Mailable.cs, Src/Coravel.Mailer/Mail/Mailers/AssertMailer.cs, Src/Coravel.Mailer/Mail/Mailers/CanSendMailWrapper.cs, Src/Coravel.Mailer/Mail/Mailers/CustomMailer.cs, Src/Coravel.Mailer/Mail/Mailers/FileLogMailer.cs, Src/Coravel.Mailer/Mail/Mailers/SmtpMailer.cs, Src/Coravel.Mailer/Mail/MessageBody.cs, Src/UnitTests/MailerUnitTests/Mail/CanSendMailWrapperTests.cs, Src/UnitTests/MailerUnitTests/Mail/CustomMailerTests.cs, Src/UnitTests/MailerUnitTests/Mail/GeneralMailTests.cs, Src/UnitTests/MailerUnitTests/Mail/InlineMailableTests.cs, Src/UnitTests/MailerUnitTests/Mail/SmtpMailerTests.cs
Breaking change: ability to set html and/or plain text body.
=> Plain-text-mail

Src/Coravel.Mailer/Coravel.Mailer.csproj
Update Mailkit from 4.3.x to 4.8.x
Update  Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation from 6.0.27 to 6.0.36
This will also fix vulnerabilities issues
Thanks
=> Update Mailkit and Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation

.github/workflows/dotnet.yml, Demo/Demo.csproj, DocsV2/docs/Mailing/README.md, Src/Coravel.Mailer/Coravel.Mailer.csproj, Src/IntegrationTests/TestMvcApp/TestMvcApp.csproj, Src/IntegrationTests/Tests/Tests.csproj, Src/UnitTests/CoravelUnitTests/CoravelUnitTests.csproj, Src/UnitTests/MailerUnitTests/MailerUnitTests.csproj
- Added documentation for mailer image embedding
- Fixed GH actions issue with dotnet versions
- Published Mailer 7.1.0
=> Add Docs For Mailer Image CID
